### ISSUE TITLE
IsNativeVhdBoot

### ISSUE THREAD

**Issue by a0rtega** [a0rtega/pafish#46]
Seen a malware sample using the new [IsNativeVhdBoot](https://msdn.microsoft.com/en-us/library/windows/desktop/hh706896(v=vs.85).aspx) function to detect if it was running in an OS booted from a VHD.

This function is only available in Windows 8 or later versions. The malware uses GetProcAddress to get the pointer to the function, and it's used if available.

![isnativevhdboot](https://cloud.githubusercontent.com/assets/1909038/11508415/0f3d4f5e-9859-11e5-8658-7b45294b491b.png)

**Comment by clshack** [comment]
Are you sure about this function ? 
I am testing it by compiling with visualstudio 2015 UPDATE 2 and I get all times "Argument error".
I am using the define found in the kit v10:

```
BOOL WINAPI TEST(
	_Out_ PBOOL NativeVhdBoot
);

BOOL bIsVhdBoot = FALSE;
::IndirectCall(L"Kernel32.dll", "IsNativeVhdBoot", &bIsVhdBoot)

```
I am using windows 10 and I tested this function on a vm.
