### ISSUE TITLE
Failure to detect Xen

### ISSUE THREAD

**Issue by tklengyel** [a0rtega/pafish#47]
On Xen 4.6 the string based detection fails as the cpuid no longer returns the string XenVMMXenVMM as the processor string. See screenshot attached. 
![pafish_xen](https://cloud.githubusercontent.com/assets/3172829/13093999/6c694356-d4c5-11e5-952d-a69e72f90e94.png)

It seems there is a separate hypervisor leaf now, as you can see in the cpuid output attached from an HVM guest.
[cpuid.txt](https://github.com/a0rtega/pafish/files/133389/cpuid.txt)

**Comment by a0rtega** [comment]
Hi,

it looks like we have been looking at the wrong value.

According to [this documentation](http://www.sandpile.org/x86/cpuid.htm#level_4000_0000h), the hypervisor name can be retrieved by issuing a `cpuid` with `EAX=4000_0000h` and the information will be returned in the registers `EBX-ECX-EDX`.

It will be fixed, thanks for your ticket!
