### ISSUE TITLE
utils.c - bug in pafish_check_mac_vendor

### ISSUE THREAD

**Issue by asafcyi** [a0rtega/pafish#49]
Hi,
I've noticed that in "pafish_check_mac_vendor" function in utils.c there is a potential problem:
palist pointer is advanced (line 167: palist = palist->Next;) and freed using LocalFree (lines: 163, 169).
It caused the program to crash.
I recommend to keep a pointer to the start of the allocated buffer and free it before leaving the function.
Thanks for this great tool!

**Comment by asafcyi** [comment]
Hi,
I've just noticed the same exists for "pafish_check_adapter_name" function in utils.c.
BR,
Asaf.

**Comment by a0rtega** [comment]
Hello there!

Thanks for your report, good catch! It has been fixed in the devel branch, it will be merged into master for the next release.

Cheers!

**Comment by a0rtega** [comment]
Merged into master and released!
