### ISSUE TITLE
linux: undefined reference to `CLSID_WbemLocator'

### ISSUE THREAD

**Issue by fe7ch** [a0rtega/pafish#50]
~/pafish/pafish$ make -f Makefile.linux
i686-w64-mingw32-gcc -c main.c -o Objects/MingW/main.o  -Wall -Wextra -O0
i686-w64-mingw32-gcc -c common.c -o Objects/MingW/common.o  -Wall -Wextra -O0
i686-w64-mingw32-gcc -c utils.c -o Objects/MingW/utils.o  -Wall -Wextra -O0
i686-w64-mingw32-gcc -c debuggers.c -o Objects/MingW/debuggers.o  -Wall -Wextra -O0
i686-w64-mingw32-gcc -c sandboxie.c -o Objects/MingW/sandboxie.o  -Wall -Wextra -O0
i686-w64-mingw32-gcc -c vbox.c -o Objects/MingW/vbox.o  -Wall -Wextra -O0
i686-w64-mingw32-gcc -c gensandbox.c -o Objects/MingW/gensandbox.o  -Wall -Wextra -O0
i686-w64-mingw32-gcc -c wine.c -o Objects/MingW/wine.o  -Wall -Wextra -O0
i686-w64-mingw32-gcc -c vmware.c -o Objects/MingW/vmware.o  -Wall -Wextra -O0
i686-w64-mingw32-gcc -c qemu.c -o Objects/MingW/qemu.o  -Wall -Wextra -O0
i686-w64-mingw32-gcc -c hooks.c -o Objects/MingW/hooks.o  -Wall -Wextra -O0
i686-w64-mingw32-gcc -c cpu.c -o Objects/MingW/cpu.o  -Wall -Wextra -O0
i686-w64-mingw32-gcc -c cuckoo.c -o Objects/MingW/cuckoo.o  -Wall -Wextra -O0
i686-w64-mingw32-gcc -c bochs.c -o Objects/MingW/bochs.o  -Wall -Wextra -O0
i686-w64-mingw32-windres Objects/MingW/pafish_private.rc --input-format=rc -o Objects/MingW/pafish_private.res -O coff
i686-w64-mingw32-gcc Objects/MingW/main.o Objects/MingW/common.o Objects/MingW/utils.o Objects/MingW/debuggers.o Objects/MingW/sandboxie.o Objects/MingW/vbox.o Objects/MingW/gensandbox.o Objects/MingW/wine.o Objects/MingW/vmware.o Objects/MingW/qemu.o Objects/MingW/hooks.o Objects/MingW/cpu.o Objects/MingW/cuckoo.o Objects/MingW/bochs.o Objects/MingW/pafish_private.res -o "Output/MingW/pafish.exe" -lwsock32 -liphlpapi -lsetupapi -lmpr -lole32 -lwbemuuid -loleaut32 -lws2_32 -s
Objects/MingW/utils.o:utils.c:(.text+0x6eb): undefined reference to `CLSID_WbemLocator'
collect2: error: ld returned 1 exit status
make: *** [Output/MingW/pafish.exe] Error 1

**Comment by a0rtega** [comment]
Hello,

could you provide the version of Ubuntu you're using to compile?

**Comment by fe7ch** [comment]
I'm sorry for delay, I hadn't access to the computer on the weekend. OS info:
Ubuntu 14.04
Linux host 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by a0rtega** [comment]
Some people are having problems to compile the project in that version of Ubuntu, and it's probably because the MingW package is a bit outdated.

I have succesfully compiled it in a more recent version of Ubuntu (15.10).
