### ISSUE TITLE
pafish & cuckoo

### ISSUE THREAD

**Issue by rayenmessaoudi** [a0rtega/pafish#60]
Hi,

I want to ask why pafish can't detect cuckoo.

**Comment by GreatBahram** [comment]
Hello @rayenmessaoudi 
Read below link and you'll understand why pafish can't detect Cuckoo VMs.
https://www.packtpub.com/mapt/book/hardware_and_creative/9781782169239/5/ch05lvl1sec32/hardening-cuckoo-sandbox-against-vm-detection

**Comment by a0rtega** [comment]
Hello,

pafish is not designed to detect any specific sandboxing product in any way. However, it can detect the underlying VM software / artifacts, or methods commonly used by sandboxes like userland hooks.

Hope it helps!
