### ISSUE TITLE
VM detection possible by checking the difference between CPU timestamp counters (rdtsc) forcing VM exit

### ISSUE THREAD

**Issue by Vaurine32** [a0rtega/pafish#63]
Hey, I have problem with this check. How to change my VMware configuration to pass this check and make my virtual machine undetectable?

**Comment by darianvaughanm** [comment]
@Vaurine32 for virtualbox i think need patch in source codes. Example - Antidetect.

**Comment by a0rtega** [comment]
See #73 for reference
