### ISSUE TITLE
Kaspersky detect this tool as Trojan

### ISSUE THREAD

**Issue by BodyDub** [a0rtega/pafish#64]
https://i.imgur.com/r6bM634.png

**Comment by crackhd** [comment]
<img width="897" alt="image" src="https://user-images.githubusercontent.com/5148375/64918476-83806d00-d753-11e9-94ac-88437f690b2f.png">
I guess this is not the biggest issue

**Comment by a0rtega** [comment]
All we can do is reporting it as a false positive to the vendors, I already did it in the Google Safebrowsing FP reporting portal: https://safebrowsing.google.com/safebrowsing/report_error/?hl=en

**Comment by a0rtega** [comment]
I removed the pafish executable from the git repository, and it's now available in the releases page. This may help getting rid of AV detections, at least in the project site.
