### ISSUE TITLE
Virtual Box rdtsc

### ISSUE THREAD

**Issue by Tribiune** [a0rtega/pafish#73]
Hello and sorry for posting here. I am using Virtual box and i am trying to make Windows 10 as stealthier as possible. Solved all pafish detections except the two rdtsc ones. I would be thankful if anyone can help with these.

Checking the difference between CPU timestamp counters (rdtsc) 
Checking the difference between CPU timestamp counters (rdtsc) forcing VM exit

**Comment by a0rtega** [comment]
We have a few issues discussing this, see #68 and #63. There are also many sources on the internet on the subject.

I don't have a solution to fix those. The only reliable way I found in the past to avoid these detections was using QEMU in full system emulation mode (not virtualization).

**Comment by Tribiune** [comment]
Thanks a lot for your response and sharing your knowledge!

**Comment by alu1al** [comment]
@Tribiune please how did you passed all the mouse detections?

**Comment by Tribiune** [comment]
I used windows 10 machine inside an Ubuntu Cuckoo Sandbox, and Cuckoo has a human interaction module that you can turn on and off that moves that mouse by itself. Also as far as i remember you can move the mouse when pafish runs and bypass it.
