### ISSUE TITLE
how to bypass this detects?

### ISSUE THREAD

**Issue by iocmet** [a0rtega/pafish#76]
![image](https://user-images.githubusercontent.com/63492966/173794782-0e428895-5a7c-4c03-a458-ac82eb842f5f.png)

**Comment by iocmet** [comment]
and how to change vmware serialnumber?
SMBIOS.use12CharSerialNumber = "TRUE"
serialNumber = "myserialnumb"
not work

**Comment by a0rtega** [comment]
See #73 for reference
